import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { ExamService } from '../Services/exam.service';
import { ExercisesService } from '../Services/exercises.service';
import { Exam } from '../Classes/Exam';
import { Exercise } from '../Classes/Exercise';
import { HttpErrorResponse } from '@angular/common/http';
import { UserDataService } from '../Services/user-data.service';
import { FormsModule } from '@angular/forms';
import { GradeService } from '../Services/grade.service';
import { Grade } from '../Classes/Grade';
import { MatDialog } from '@angular/material/dialog';
import { ViewGradeDialogComponent } from '../view-grade-dialog/view-grade-dialog.component';
@Component({
  selector: 'app-send-code-page',
  templateUrl: './send-code-page.component.html',
  styleUrls: ['./send-code-page.component.css']
})
export class SendCodePageComponent {
  enteredExamId: string = '';
  exam: Exam | null = null;
  exercises: Exercise[] = [];
  selectedAnswers: { [key: number]: string } = {};
  constructor(private examService: ExamService, private exercisesService: ExercisesService, private userDataService: UserDataService, private gradeService: GradeService, private dialog: MatDialog) { }

  checkAndOpenExam() {
    const enteredIdAsNumber = Number(this.enteredExamId);
    if (!isNaN(enteredIdAsNumber)) {
      console.log('Fetching exam details...');
      this.examService.getExamById(enteredIdAsNumber).subscribe(
        exam => {
          if (exam) {
            console.log('Exam details fetched:', exam);

            this.exam = exam;

            // Use getExercisesByExamId method to fetch exercises
            this.tryGetExercisesByExamId(exam.id);

          } else {
            console.log('Exam not found');
          }
        },
        error => {
          if (error.status === 302 && error.error) {
            console.log('Redirected to exam:', error.error);
            this.exam = error.error;

            // Use getExercisesByExamId method to fetch exercises
            this.tryGetExercisesByExamId(this.exam?.id);

          } else {
            console.error('Error fetching exam by ID:', error);
          }
        }
      );
    } else {
      console.log('Invalid exam ID format');
    }
  }
  public logout(){
    this.userDataService.logout();
  }

  submitExercises(event: Event) {
    event.preventDefault();

    let correctAnswersCount = 0;

    this.exercises.forEach((exercise, index) => {
      if (this.selectedAnswers[index] === exercise.answer) {
        console.log(`Exercise ${index + 1}: Correct`);
        correctAnswersCount++;
      } else {
        console.log(`Exercise ${index + 1}: Incorrect`);
      }
    });

    // Calculate the grade
    const grade = (correctAnswersCount / this.exercises.length) * 10;
    console.log(`Grade: ${grade.toFixed(2)}`);

    if (this.exam && this.userDataService.getUserData()) {
      const newGrade: Grade = {
        id: 0, // Assuming ID is generated by the backend
        value: grade, // Replace with your calculated grade value
        student: this.userDataService.getUserData(),
        exam: this.exam,
        exam_id: this.exam.id,
        student_id: this.userDataService.getUserData().id,
        average: 0, // Set as needed
        
      };

    // Call the GradeService to create the grade
    this.gradeService.createGrade(newGrade).subscribe(
      createdGrade => {
        console.log('Grade created successfully:', createdGrade);
        this.openGradeDialog(createdGrade);
      },
      error => {
        console.error('Error creating grade:', error);
      }
    );
  }else {
    console.error('Error: Exam or Student information is missing');
    // Handle missing exam or student information
  }

}

private openGradeDialog(grade: Grade): void {
  // Open the dialog with GradeDialogComponent
  const dialogRef = this.dialog.open(ViewGradeDialogComponent, {
    data: { grade }, // Pass the grade to the dialog
  });

  // You can subscribe to dialog close events if needed
  dialogRef.afterClosed().subscribe(result => {
    console.log('Dialog closed:', result);
    // Additional logic after dialog close
  });
}

  private tryGetExercisesByExamId(examId: number | undefined): void {
    if (examId !== undefined) {
      console.log('Fetching exercises...');
      this.getExercisesByExamId(examId);
    }
  }

  private getExercisesByExamId(examId: number): void {
    this.exercisesService.getExercisesByExamId(examId).subscribe(
      (exercises: Exercise[]) => {
        console.log('Exercises fetched:', exercises);
        this.exercises = exercises;
      },
      (error: HttpErrorResponse) => {
        console.error('Error fetching exercises:', error);
      }
    );
  }
}
